# Render configuration for GEI Unified Platform
# Despliegue automático sin configuración manual

services:
  - type: web
    name: gei-unified-platform
    env: node
    buildCommand: npm install && npm run build
    startCommand: ./scripts/start-production-optimized.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true

  # Base de datos PostgreSQL
  - type: pserv
    name: gei-postgres
    env: postgresql
    plan: starter
    ipAllowList: []
    maxConnections: 10
    autoDeploy: true
    branch: main

databases:
  - name: gei-postgres
    databaseName: gei_unified
    user: gei_user
    plan: starter
    ipAllowList: []
    autoDeploy: true 