services:
  - type: web
    name: eduai-platform
    env: node
    plan: starter
    buildCommand: |
      npm ci
      npm run build:server
      npm run build:client
    startCommand: |
      chmod +x scripts/start-render.sh
      ./scripts/start-render.sh
    envVars:
      # Configuración del servidor
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: HOST
        value: 0.0.0.0
      
      # Base de datos PostgreSQL (Render)
      - key: DB_HOST
        value: dpg-d1uvb5ur433s73f5prpg-a.frankfurt-postgres.render.com
      - key: DB_NAME
        value: gei_db
      - key: DB_USER
        value: gei_db_user
      - key: DB_PASSWORD
        value: pV89ToE3mgCR8BMidIvsTubt2SycbqBB
      - key: DB_PORT
        value: 5432
      - key: DB_SSL
        value: true
      
      # URL completa de la base de datos
      - key: DATABASE_URL
        value: postgresql://gei_db_user:pV89ToE3mgCR8BMidIvsTubt2SycbqBB@dpg-d1uvb5ur433s73f5prpg-a.frankfurt-postgres.render.com:5432/gei_db?sslmode=require
      
      # Clave secreta para sesiones
      - key: SESSION_SECRET
        value: gei_adeptify_session_secret_2024_secure_key_123456789_abcdefghijklmnop
      
      # JWT Secrets
      - key: JWT_SECRET
        value: gei_jwt_secret_2024_secure_key_123456789_abcdefghijklmnop
      - key: JWT_REFRESH_SECRET
        value: gei_jwt_refresh_secret_2024_secure_key_123456789_abcdefghijklmnop
      - key: JWT_EXPIRES_IN
        value: 24h
      
      # Google OAuth Configuration
      - key: GOOGLE_CLIENT_ID
        value: 1080986221149-kk92eavrakaci64feloqtne5p79inphp.apps.googleusercontent.com
      - key: GOOGLE_CLIENT_SECRET
        value: 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
      - key: GOOGLE_CALLBACK_URL
        value: https://gei.adeptify.es/auth/google/callback
      - key: GOOGLE_REDIRECT_URI
        value: https://gei.adeptify.es/auth/google/callback
      
      # Google Gemini AI API
      - key: GEMINI_API_KEY
        value: AIzaSyB9bwid0oHPk-1ettsSdCU_IpzsMFojscc
      
      # Configuración adicional
      - key: LOG_LEVEL
        value: info
      - key: CORS_ORIGIN
        value: https://gei.adeptify.es
      - key: ALLOWED_ORIGINS
        value: https://gei.adeptify.es,https://www.gei.adeptify.es
      - key: ENABLE_METRICS
        value: true
      - key: ENABLE_DEBUG_LOGS
        value: false
      - key: ENABLE_AUDIT_LOGS
        value: true
      
      # URLs de producción
      - key: PRODUCTION_URL
        value: https://gei.adeptify.es
      - key: API_BASE_URL
        value: https://gei.adeptify.es/api
      - key: CLIENT_BASE_URL
        value: https://gei.adeptify.es
      - key: FRONTEND_URL
        value: https://gei.adeptify.es
      
      # Configuración de módulos
      - key: ADEPTIFY_ENABLED
        value: true
      - key: ASSISTATUT_ENABLED
        value: true
      - key: ENABLE_CACHE
        value: true
      - key: ENABLE_RATE_LIMITING
        value: true
      
      # Variables opcionales (pueden configurarse manualmente en Render)
      - key: REDIS_URL
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
    healthCheckPath: /health
    autoDeploy: true

databases:
  - name: eduai-postgres
    databaseName: gei_db
    user: gei_db_user
    plan: starter

  - name: eduai-redis
    databaseName: redis
    plan: starter
