services:
  - type: web
    name: eduai-platform-frontend
    env: node
    buildCommand: cd client && npm install && npm run build
    startCommand: cd client && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://api.eduai-platform.com
      - key: VITE_MCP_URL
        value: https://eduai-platform.com

  - type: web
    name: eduai-platform-api
    env: docker
    dockerfilePath: ./Dockerfile.api
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: eduai-platform-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: eduai-platform-redis
          property: connectionString

  - type: redis
    name: eduai-platform-redis
    ipAllowList: []

  - type: pserv
    name: eduai-platform-db
    env: postgres
    plan: standard-0
    ipAllowList: []

databases:
  - name: eduai-platform-db
    databaseName: eduai_platform_prod
    user: eduai_user
